---
- name: open relevant ports (Bastion)
  tags: bastion,pihole,firewalld,firewall,dns
  firewalld:
    zone: public
    permanent: true
    immediate: yes
    rich_rule: "{{ item }}"
    state: enabled
  with_items:
    - 'rule family="ipv4" port port="80" protocol="tcp" accept'
    - 'rule family="ipv4" port port="443" protocol="tcp" accept'
    - 'rule family="ipv4" port port="53" protocol="tcp" accept'
    - 'rule family="ipv4" port port="53" protocol="udp" accept'
  notify: reload firewall
