---
- hosts: all
  become: true
  tags: always
  pre_tasks:
    - name: update repositiories (Debian)
      tags: always
      apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: update repositories (Arch)
      tags: always
      pacman:
        update_cache: yes
      changed_when: false
      when: ansible_distribution in ["Arch Linux", "Archlinux", "Manjaro"]

- hosts: all
  tags: always
  become: true
  gather_facts: false
  roles:
    - base

- hosts: bastion_hosts
  tags: bastion
  become: true
  gather_facts: false
  roles:
    - bastion

- hosts: bastion-new-hosts
  tags: bastion-new
  become: true
  gather_facts: false
  roles:
    - bastion-new

- hosts: hyperion_hosts
  tags: hyperion
  become: true
  gather_facts: false
  roles:
    - hyperion

- hosts: git_hosts
  tags: git
  become: true
  gather_facts: false
  roles:
    - git

- hosts: plex_hosts
  tags: plex,media
  become: true
  gather_facts: false
  roles:
    - plex

- hosts: workstation_hosts
  tags: worksation,workstations
  become: true
  gather_facts: false
  roles:
    - workstation

- hosts: jspc*
  tags: jspc
  become: true
  gather_facts: false
  roles:
    - jspc001

#- hosts: jspc002
  #tags: jspc002
  #become: true
  #gather_facts: false
  #roles:
    #- jspc002

#- hosts: jspc003
  #tags: jspc003
  #become: true
  #gather_facts: false
  #roles:
    #- jspc003

- hosts: jfpc*
  tags: jfpc
  become: true
  gather_facts: false
  roles:
    - jfpc001
