---
- name: open HTTP/S port (Hyperion)
  tags: hyperion,ufw
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item[0] }}"
    src: "{{ item[1] }}"
  with_nested:
    - ["8090", "9092"]
    - ["192.168.0.0/24", "10.0.0.0/24", "fd7e:bc9e:8275:e9cc::/64"]

- name: open remaining/misc ports (Hyperion)
  tags: hyperion,ufw
  ufw:
    rule: allow
    port: "{{ item[0] }}"
    src: "{{ item[1] }}"
  with_nested:
    - ["19333", "19400", "19444", "19445"]
    - ["192.168.0.0/24", "10.0.0.0/24", "fd7e:bc9e:8275:e9cc::/64"]
