---
- name: create ansible user
  tags: always
  user:
    name: ansible
    system: yes

- name: copy sudoers_ansible
  tags: always
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: create .ssh dir if it doesn't exist
  tags: always
  file:
    path: /home/ansible/.ssh
    state: directory
    mode: "0700"

- name: add ssh keys for access
  tags: always
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFDCQUSwXVYUn0x4dfrBYQxeYbAi94LZiYTGTzUhitDP Ansible-management"
