---
- name: create ansible log directory (ansible-pull)
  tags: base,core,cron,ansible,log,logs
  file:
    path: /var/log/ansible
    state: directory
    owner: ansible
    group: ansible
    mode: 0755

- name: setup ansible logrotate (ansible-pull)
  tags: base,core,ansible,log,logs,logrotate
  copy:
    src: files/logrotate_ansible
    dest: /etc/logrotate.d/ansible
    owner: root
    group: root
    mode: 0644
