---
- name: install updates (Debian)
  tags: always
  apt:
    upgrade: full
    update_cache: no
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install updates (Arch)
  tags: always
  pacman:
    upgrade: yes
    update_cache: no
  when: ansible_distribution in ["Arch Linux", "Archlinux", "Manjaro"]

- name: install updates (Fedora)
  tags: always
  dnf:
    name: "*"
    update_cache: no
    state: latest
  when: ansible_distribution in ["Fedora"]
