---
- name: setup vault
  tags: vault
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: copy the vault key
      tags: vault
      copy:
        src: ~/.vault_key
        dest: /home/ansible/.vault_key
        mode: 0600
        owner: ansible
        group: ansible
