---
- name: bootstrap
  tags: ansible
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: create ansible user
      tags: ansible
      user:
        name: ansible
        system: yes
